
export const styleElement = [
    {
      title: "STYLE",
      element: [
        "Abstract",
        "Fine Art",
        "Modern",
        "Abstract Expressionism",
        "Figurative",
        "Impressionism",
        "Realism",
        "Conceptual",
        "Minimalism",
        "Pop Art",
        "Pop Art",
        "Portraiture",
        "Surrealism",
        "Art Deco",
        "Illustration",
        "Street Art",
        "Photorealism",
        "Cubism",
        "Folk",
        "Documentary",
        "Dada",
      ],
    },
  ];
  export const subjectElement = [
    {
      title: "SUBJECT",
      element: [
        "Abstract",
        "Landscape",
        "Portrait",
        "People",
        "Animal",
        "floral",
        "Nature",
        "women",
        "Still Life",
        "Seascape",
        "Fantasy",
        // "Cities",
        // "Architecture",
        // "Body",
        // "Botanic",
        // "Beach",
        "Geometric",
        // "Love",
        // "Culture",
        // "Men",
        // "Pop Culture/Celebrity",
        // "Erotic",
        // "World Culture",
        // "Children",
        // "Music",
        "Religious",
        "Popular culture",
        "Classical mythology",
        // "Garden",
        // "Interiors",
        // "Places",
        // "Tree",
        // "Celebrity",
        // "Water",
        // "Boat",
        // "Horse",
        // "Food",
        // "Fashion",
        // "Political",
        // "Performing Arts",
        // "Religion",
        // "Fish",
        "Graffiti",
        // "Outer Space",
        // "Mortality",
        "Calligraphy",
        // "Cats",
        // "Family",
        // "Aerial",
        // "Dogs",
        // "Food & Drink",
        // "Light",
        // "Cartoon",
        // "Home",
        // "Travel",
        // "Humor",
        // "Sailboat",
        // "Cinema",
        "Rural life",
        "Seasons",
        // "Sport",
        // "Patterns",
        // "Car",
        // "Sports",
        // "Time",
        // "Automobile",
        // "Kids",
        // "Comics",
        // "Science/Technology",
        // "Politics",
        // "Language",
        // "Health & Beauty",
        // "Science",
        // "Ship",
        // "Typography",
        // "Transportation",
        // "Bicycle",
        // "Business",
        // "Airplane",
        // "Technology",
        // "Wall",
        // "Cows",
        // "Cuisine",
        // "Train",
        // "Education",
        // "Aeroplane",
        // "Yacht",
        // "Kitchen",
        // "Motorcycle",
        // "Bike",
        // "Motorbike",
        // "Motor",
        "Figurative",
      ],
    },
  ];
  export const mediumElement = [
    {
      title: "MEDIUM",
      element: [
        "Acrylic",
        "Oil",
        "Watercolor",
        "Ink",
        "Spray Paint",
        "Gesso",
        "Paper",
        "Paint",
        "Gouache",
        "Pastel",
        "Pencil",
        "Digital",
        "Charcoal",
        "Graphite",
        "Color",
        // "Enamel",
        // "Marker",
        "Tempera",
        // "Household",
        // "Airbrush",
        "Fabric",
        // "Resin",
        // "Wax",
        // "Wood",
        // "Chalk",
        // "Textile",
        // "Plaster",
        "Black & White",
        // "Metal",
        // "Photo",
        // "Ballpoint Pen",
        // "Found Objects",
        // "Conte",
        // "Latex",
        // "Stencil",
        // "Manipulated",
        // "Plastic",
        // "Fiber",
        // "Vector",
        // "Screenprinting",
        // "Encaustic",
        // "Monotype",
        // "Glass",
        // "Stone",
        // "C-type",
        // "Clay",
        // "Crayon",
        // "3D Sculpting",
        "Lithograph",
        // "Environmental",
        // "Ceramic",
        // "Neon",
        // "Dye Transfer",
        // "Full spectrum",
        // "Paper mache",
        // "Gelatin",
        // "Marble",
        // "Photogram",
        // "Engraving",
        // "Mosaic",
        // "Woodcut",
        // "Silverpoint",
        // "Aquatint",
        // "Linocuts",
        // "Kinetic",
        // "Bronze",
        // "Steel",
        // "Algorithmic Art",
        // "Leather",
        // "Giclée",
        // "Lights",
        // "Interactive",
        // "Fiberglass",
        // "Rubber",
        // "Etching",
        // "Fractal",
        // "LED",
        // "Timber",
        // "Platinum",
        // "Sound",
        // "Polaroid",
        // "Drypoint",
        // "Granite",
        // "Pottery",
        // "Robotics",
        // "Pen and Ink",
        // "Decoupage",
        // "Lenticular",
        // "Taxidermy",
        // "Mezzotint",
        // "Pinhole",
      ],
    },
  ];

  export const materialElement = [
    {
      title: "MATERIAL",
      element: [
        "Canvas",
        "Paper",
        "Wood",
        "Other",
        "Cardboard",
        "Soft (Yarn, Cotton, Fabric)",
        // "Plastic",
        // "Aluminium",
        // "Glass",
        // "acrylic",
        // "Carbon Fibre",
        // "Linen",
        // "Oil",
        // "Canvas board",
        // "Bronze",
        // "Steel",
        // "Stone",
        // "Panel",
        // "Marble",
        // "Ceramic",
        // "Iron",
        // "Oil Paint",
        // "Paint",
        // "Ink",
        // "Stainless Steel",
        // "Wood Panel",
        // "Acrylic Paint",
        // "Canvas Panel",
        // "Masonite",
        // "Watercolor",
        // "Varnish",
        // "Stretched Canvas",
        // "Gesso",
        // "Gold Leaf",
        // "Sound",
        // "Watercolor Paper",
        // "Mdf",
        // "Resin",
        // "Acrylic On Gallery-wrapped Canvas",
        // "Oil On Canvas",
        // "Sand",
        // "Linen Canvas",
        // "Hardboard",
        // "High Quality Professional Oil Art Paints, Canvas, Covered With Protective Varnish",
        // "Mixed Media",
        // "Acrylic On Canvas",
        // "Acrylics",
        // "High Quality Professional Oil Art Paints, Italian Linen Canvas, Covered With Protective Varnish",
        // "Charcoal",
        // "Pencil",
        // "Silk",
        // "Encaustic",
        // "Plexiglass",
        // "Watercolour",
        // "Pastel",
        // "Plywood",
        // "Collage",
        // "Digital",
        // "Plaster",
        // "Acid Free Canson Paper",
        // "Gold",
        // "Mdf Board",
        // "Acrylic Paints",
        // "Mdf Wood Panel",
        // "Spray paint",
        // "Newspaper",
        // "Frame",
        // "Marker",
        // "Oil Pastel",
        // "Raw Canvas",
        // "Wood Frame",
        // "Oil Paints",
        // "Palette Knife",
        // "Canvas Paper",
        // "Acrylic sealant",
        // "Carton",
        // "Unstretched Canvas",
        // "Wax",
        // "Graphite",
        // "Alcohol Ink",
        // "Rice Paper",
        // "Japanese Paper",
        // "Pigments",
        // "Arches 100 Percent Cotton Watercolor Paper",
        // "Fine Art Paper",
        // "Papyrus",
        // "Brush",
        // "Texture",
        // "Acid Free Foam Core Backing",
        // "Cotton Canvas",
        // "Glitter",
        // "Acrylic. Mixed Material",
        // "Rolled Canvas",
        // "Silver Leaf",
        // "Photography",
        // "Yupo",
        // "Canvasboard",
        // "Metal",
        // "Oil Painting",
        // "Textile",
      ],
    },
  ];

  export const priceElement = [
    {
      title: "PRICE",
      element: [
        "Under ₹500",
        "₹500 - ₹1,000",
        "₹1,000 - ₹2,000",
        "₹2,000 - ₹5,000",
        "₹5,000 - ₹10,000",
        "Over ₹10,000",
      ],
    },
  ];

  export const sizeElement = [
    {
      title: "SIZE",
      element: ["Small", "Medium", "Large", "Oversized"],
    },
  ];

  export const orientationElement = [
    {
      title: "ORIENTATION",
      element: ["Horizontal", "Vertical", "Square"],
    },
  ];

  export const colorElement = [
    {
      title: "COLOR",
      element: [],
    },
  ];

  export const artistCountryElement = [
    {
      title: "ARTIST COUNTRY",
      element: [
        "United States",
        "United Kingdom",
        "Germany",
        "France",
        "Spain",
        "Italy",
        "Canada",
        "Netherlands",
        "Ukraine",
        "India",
        "Poland",
        "Australia",
        "Hungary",
        "Turkey",
        "Serbia",
        "Romania",
        "Bulgaria",
        "South Korea",
        "Israel",
        "Belgium",
        "Czech Republic",
        "Greece",
        "Switzerland",
        "Japan",
        "Austria",
        "Portugal",
        "Pakistan",
        "Brazil",
        "Latvia",
        "Mexico",
        "Argentina",
        "Slovakia",
        "Armenia",
        "China",
        "Georgia",
        "Vietnam",
        "Indonesia",
        "Lithuania",
        "Sweden",
        "South Africa",
        "Moldova",
        "Ireland",
        "Slovenia",
        "Norway",
        "Kazakhstan",
        "Nigeria",
        "Estonia",
        "Thailand",
        "Croatia",
        "Finland",
        "Colombia",
        "United Arab Emirates",
        "Egypt",
        "Sri Lanka",
        "Denmark",
        "Cyprus",
        "New Zealand",
        "Macedonia",
        "Uruguay",
        "Chile",
        "Singapore",
        "Hong Kong",
        "Azerbaijan",
        "Kenya",
        "Bangladesh",
        "Uzbekistan",
        "Mozambique",
        "Luxembourg",
        "Malaysia",
        "Ghana",
        "Taiwan",
        "Lebanon",
        "Philippines",
        "Montenegro",
        "Costa Rica",
        "Bosnia and Herzegovina",
        "Ecuador",
        "Saint Martin",
        "Peru",
        "Venezuela",
        "Iceland",
        "United States Minor Outlying Islands",
        "Kyrgyzstan",
        "Albania",
        "Jamaica",
        "Uganda",
        "Malta",
        "Morocco",
        "Trinidad and Tobago",
        "Qatar",
        "Puerto Rico",
        "Saudi Arabia",
        "Paraguay",
        "Sint Maarten",
        "Tunisia",
        "Russia",
        "Jordan",
        "Kosovo",
        "Monaco",
        "Nicaragua",
      ],
    },
  ];

  export const featuredArtistElement = [
    {
      title: "FEATURED ARTIST",
      element: [
        "Artkya Catalog",
        "Inside The Studio",
        "Rising Stars",
        "One To Watch",
        "The Other Art Fair",
      ],
    },
];
  
export const CategoryItem = [
  {
    title: "Category",
    element: [
      "Paintings"
    ],
  },
]